language: python
python:
  - "2.7"
  - "3.5.1"

# command to install dependencies
before_install:
  - pip install codecov pyserial flask future

install:
# command to run tests
script:
  - python tests.py
  - coverage run tests.py

after_success:
  - codecov
