language: python
python:
  - "2.7.6"

# command to install dependencies
install:
# command to run tests
script: python run_testsuite.py

before_install:
  - pip install codecov
after_success:
  - codecov
