language: python
python:
  - "2.7"

# command to install dependencies
before_install:
  - pip install codecov pyserial

install:
# command to run tests
script:
  - python tests.py
  - coverage run tests.py

after_success:
  - codecov
